import os
import subprocess
import shutil
import argparse

# --- Constants & Paths ---
RES_BK = "01_backups/01_resources"
POL_BK = "01_backups/02_policies"
SITE_BK = "01_backups/03_sites"

def run_step(name, command, cwd):
    print(f"[*] Starting: {name}")
    root_dir = os.getcwd() 
    env = os.environ.copy()
    env["PYTHONPATH"] = f"{root_dir}:{env.get('PYTHONPATH', '')}"

    try:
        subprocess.run(command, cwd=cwd, check=True, shell=True, env=env)
        print(f"[+] {name} Success.\n")
    except subprocess.CalledProcessError as e:
        print(f"[!] {name} Failed: {e}\n")

def pull_resources():
    run_step("Pull Resources", "python3 pull_resources_refactored.py", "02_policy_scripts")
    shutil.copy("02_policy_scripts/resourceconfig.yml", f"{RES_BK}/latest_resources.yml")

def pull_policies():
    # 1. Run the new Master Pull script that generates individual files
    # Note: Using the filename you just verified: pull_policy_master.py
    run_step("Pull Master Policies", "python3 pull_policy_master.py -PT all", "02_policy_scripts")
    
    # 2. List of files generated by the master script
    policy_files = [
        "path_policyconfig.yml",
        "qos_policyconfig.yml",
        "nat_policyconfig.yml",
        "security_policyconfig.yml",
        "performance_policyconfig.yml"
    ]
    
    # 3. Move each file to the backup directory
    print(f"[*] Archiving policies to {POL_BK}...")
    for pf in policy_files:
        src = f"02_policy_scripts/{pf}"
        dst = f"{POL_BK}/{pf}" # You can rename to 'latest_path.yml' etc. if you prefer
        if os.path.exists(src):
            shutil.copy(src, dst)
            print(f"    [OK] Archived {pf}")

def pull_sites():
    site_cmd = f'python3 pull_site.py -S ALL_SITES --multi-output "../{SITE_BK}"'
    run_step("Pull Site Configs", site_cmd, "03_config_tool")

def main():
    parser = argparse.ArgumentParser(description="SD-WAN Multi-Level Backup Orchestrator")
    parser.add_argument("-R", "--resources", action="store_true", help="Pull only Resources")
    parser.add_argument("-P", "--policies", action="store_true", help="Pull only Policies")
    parser.add_argument("-S", "--sites", action="store_true", help="Pull only Sites")
    args = parser.parse_args()

    run_all = not (args.resources or args.policies or args.sites)

    if args.resources or run_all:
        pull_resources()
    
    if args.policies or run_all:
        pull_policies()
    
    if args.sites or run_all:
        pull_sites()

    print(f"Backup operation complete.")

if __name__ == "__main__":
    main()